version: 2
project_name: autohost

release:
  draft: false
  prerelease: auto

builds:
  - id: autohost
    main: .                 # ← raíz: donde está tu main.go
    binary: autohost
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [ -trimpath ]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: binario_plano
    ids: [autohost]                         # ← en v2 usa 'ids' (no 'builds')
    formats: [binary]                       # ← en v2 usa 'formats' (no 'format')
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  sort: asc
  filters:
    exclude: ['^docs?:', '^chore:', '^test:', '^ci:']
